// <auto-generated />
using LaptopAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaptopAPI.Migrations.Registration
{
    [DbContext(typeof(RegistrationContext))]
    [Migration("20201229141122_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LaptopAPI.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nVarchar(100)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nVarchar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("nVarchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("nVarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nVarchar(10)");

                    b.HasKey("RegistrationId");

                    b.ToTable("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
